apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 55680
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:55680"
    processors:
    extensions:
      health_check: {}
    exporters:
      stackdriver:
        # TODO: replace $PROJECT_ID
        project: $PROJECT_ID
        # endpoint: test-endpoint
        user_agent: my-collector {{version}}
        use_insecure: true
        timeout: 12s
        number_of_workers: 3

        #   - source_type: source.resource1
        #     target_type: target-resource1
        #     label_mappings:
        #       - source_key: contrib.opencensus.io/exporter/stackdriver/project_id
        #         target_key: project_id
        #         optional: true
        #       - source_key: source.label1
        #         target_key: target_label_1

        trace:
          bundle_delay_threshold: 2s
          bundle_count_threshold: 50
          bundle_byte_threshold: 15e3
          bundle_byte_limit: 0
          buffer_max_bytes: 8e6

        metric:
          prefix: custom.googleapis.com
          skip_create_descriptor: true
      logging:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [stackdriver]

        metrics:
          receivers: [otlp]
          processors: []
          exporters: [stackdriver, logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp # Default endpoint for otlp receiver.
      port: 55680
      protocol: TCP
      targetPort: 55680
      nodePort: 30080
    # - name: metrics # Default endpoint for metrics.
    #   port: 8889
    #   protocol: TCP
    #   targetPort: 8889
  selector:
    component: otel-collector
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      # annotations:
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "8889"
      #   prometheus.io/scrape: "true"
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - command:
            - "/otelcontribcol"
            - "--config=/conf/otel-collector-config.yaml"
            # Memory Ballast size should be max 1/3 to 1/2 of memory.
            - "--mem-ballast-size-mib=683"
          env:
            - name: GOGC
              value: "80"
          image: otel/opentelemetry-collector-contrib:0.18.0
          name: otel-collector
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 55680 # Default endpoint for otlp receiver.
            # - containerPort: 8889 # Default endpoint for querying metrics.
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          # - name: otel-collector-secrets
          #   mountPath: /secrets
          livenessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
          readinessProbe:
            httpGet:
              path: /
              port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem
